apiVersion: v1
kind: ConfigMap
metadata:
  name: forail-settings
  namespace: {{ include "forail.namespace" . }}
  labels:
    {{- include "forail.componentLabels" (dict "root" . "component" "settings") | nindent 4 }}
data:
{{- range $path, $_ := .Files.Glob "files/settings/*.py" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forail-receptor
  namespace: {{ include "forail.namespace" . }}
  labels:
    {{- include "forail.componentLabels" (dict "root" . "component" "receptor") | nindent 4 }}
data:
  receptor.conf: |
{{ .Files.Get "files/receptor/receptor.conf" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forail-scripts
  namespace: {{ include "forail.namespace" . }}
  labels:
    {{- include "forail.componentLabels" (dict "root" . "component" "scripts") | nindent 4 }}
data:
{{- range $path, $_ := .Files.Glob "files/scripts/*.sh" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forail-otel-config
  namespace: {{ include "forail.namespace" . }}
  labels:
    {{- include "forail.componentLabels" (dict "root" . "component" "otel-collector") | nindent 4 }}
data:
  config.yaml: |
{{ .Files.Get "files/otel/config.yaml" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forail-nginx-internal
  namespace: {{ include "forail.namespace" . }}
  labels:
    {{- include "forail.componentLabels" (dict "root" . "component" "web") | nindent 4 }}
data:
  nginx.conf: |
{{ .Files.Get "files/nginx/nginx-internal.conf" | indent 4 }}
