apiVersion: v1
kind: Secret
metadata:
  name: forail-secrets
  namespace: {{ include "forail.namespace" . }}
  labels:
    {{- include "forail.componentLabels" (dict "root" . "component" "secrets") | nindent 4 }}
type: Opaque
stringData:
  postgresPassword: {{ .Values.secrets.postgresPassword | quote }}
  forailSecretKey: {{ .Values.secrets.forailSecretKey | quote }}
  forailBroadcastWebsocketSecret: {{ .Values.secrets.forailBroadcastWebsocketSecret | quote }}
  forailAdminPassword: {{ .Values.secrets.forailAdminPassword | quote }}
