apiVersion: v1
kind: Secret
metadata:
  name: forge-secrets
  namespace: {{ include "forge.namespace" . }}
  labels:
    {{- include "forge.componentLabels" (dict "root" . "component" "secrets") | nindent 4 }}
type: Opaque
stringData:
  postgresPassword: {{ .Values.secrets.postgresPassword | quote }}
  forgeSecretKey: {{ .Values.secrets.forgeSecretKey | quote }}
  forgeBroadcastWebsocketSecret: {{ .Values.secrets.forgeBroadcastWebsocketSecret | quote }}
  forgeAdminPassword: {{ .Values.secrets.forgeAdminPassword | quote }}
